global:
  scrape_interval: 10s
  evaluation_interval: 30s
scrape_configs:
  - job_name: spring-monitoring
    honor_labels: true
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['main:8080']